### ISSUE TITLE
Pop-Location isn't working after Enter-Location was used

### ISSUE THREAD

**Issue by codecraft-software** [codecraft-team/PSDT.Location#3]
Actual: Pop-Location cannot be used to navigate back to previous location, after Enter-Location was used.
Expected: The caller's location stays the same, when Pop-Location is called after Enter-Location.

Possible root cause of the problem: Enter-Location isn't using the global location stack of the caller. The module is using its own session state, which separates the location stack from the caller's (global) location stack.

**Comment by JozsefHorvath** [comment]
The fix was merged into the master.
